solution for LeetCode 24
izaLukawska/LeetCode pull request #28
Opened 2024-11-19 14:45 UTC by izaLukawska

2024-11-19 17:05 UTC, Wlodek-YouCanDev requested changes

2024-11-19 17:05 UTC, Wlodek-YouCanDev commented on src/LeetCode/Java_Problems/LeetCode_24.java
> +	}
Gdzie odstęp?

2024-11-19 17:05 UTC, Wlodek-YouCanDev commented on src/LeetCode/Java_Problems/LeetCode_24.java
> +	public static class ListNode {
Dlaczego klasa publiczna jeśli tylko tu jej używasz?

2024-11-19 18:12 UTC, izaLukawska commented
code refactored, ready for review

2024-11-24 11:01 UTC, Wlodek-YouCanDev approved these changes

2024-11-24 12:12 UTC, merged